# flexoki-light ¡ª Trimum Ubuntu Theme
export TRIMUM_THEME_NAME="flexoki-light"
export TRIMUM_THEME_VARIANT="light"
export TRIMUM_BG="#fffcf0"
export TRIMUM_SURFACE="#f2f0e5"
export TRIMUM_OVERLAY="#b7b5ac"
export TRIMUM_SUBTEXT="#6f6e69"
export TRIMUM_TEXT="#100f0f"
export TRIMUM_ACCENT="#b3603a"
export TRIMUM_RED="#b3453a"
export TRIMUM_GREEN="#879a55"
export TRIMUM_YELLOW="#d6a04a"
export TRIMUM_BLUE="#4385be"
export TRIMUM_PINK="#b34572"
export TRIMUM_GTK_THEME="flexoki-light"
export TRIMUM_ICON_THEME="flexoki-light"
export TRIMUM_CURSOR_THEME="Yaru"
export TRIMUM_TERMINAL_THEME="flexoki-light"
export TRIMUM_WALLPAPER="themes/flexoki-light/backgrounds/default.jpg"
