# everforest ¡ª Trimum Ubuntu Theme
export TRIMUM_THEME_NAME="everforest"
export TRIMUM_THEME_VARIANT="dark"
export TRIMUM_BG="#2b3339"
export TRIMUM_SURFACE="#2d3c46"
export TRIMUM_OVERLAY="#545c5e"
export TRIMUM_SUBTEXT="#859289"
export TRIMUM_TEXT="#d3c6aa"
export TRIMUM_ACCENT="#a7c080"
export TRIMUM_RED="#e67e80"
export TRIMUM_GREEN="#83c092"
export TRIMUM_YELLOW="#dbbc7f"
export TRIMUM_BLUE="#7fbbb3"
export TRIMUM_PINK="#d699b6"
export TRIMUM_GTK_THEME="everforest"
export TRIMUM_ICON_THEME="everforest"
export TRIMUM_CURSOR_THEME="Yaru"
export TRIMUM_TERMINAL_THEME="everforest"
export TRIMUM_WALLPAPER="themes/everforest/backgrounds/default.jpg"
