"""`trm completion` command — print a shell completion script (bash / zsh / fish).

The command list is derived at call time from the registry
(``collect_commands``); nothing is hard-coded, so new commands are picked up
without regenerating a script. Completion covers command and subcommand names
only — no flag completion in this slice.
"""

from __future__ import annotations

import argparse

from ..registry import collect_commands


def _names() -> tuple[list[str], dict[str, list[str]]]:
    """Compute (top-level names, {group: subcommand names}) from the registry."""
    infos = collect_commands()
    top = sorted({info.path[0] for info in infos if info.path})
    groups: dict[str, set[str]] = {}
    for info in infos:
        if len(info.path) == 2:
            groups.setdefault(info.path[0], set()).add(info.path[1])
    group_names = {name: sorted(subs) for name, subs in groups.items()}
    return top, group_names


def _build_bash() -> str:
    top, groups = _names()
    lines = [
        "# trm bash completion (generated by `trm completion bash`)",
        "_trm_complete() {",
        "    local cur",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        "    COMPREPLY=()",
        '    if [ "${COMP_CWORD}" -eq 1 ]; then',
        f'        COMPREPLY=($(compgen -W "{" ".join(top)}" -- "$cur"))',
        '    elif [ "${COMP_CWORD}" -eq 2 ]; then',
        '        case "${COMP_WORDS[1]}" in',
    ]
    for group, subs in sorted(groups.items()):
        lines.append(f"            {group})")
        lines.append(f'                COMPREPLY=($(compgen -W "{" ".join(subs)}" -- "$cur"))')
        lines.append("                ;;")
    lines.append("            *)")
    lines.append("                ;;")
    lines.append("        esac")
    lines.append("    fi")
    lines.append("}")
    lines.append("complete -F _trm_complete trm")
    return "\n".join(lines) + "\n"


def _build_zsh() -> str:
    top, groups = _names()
    lines = [
        "#compdef trm",
        "# trm zsh completion (generated by `trm completion zsh`)",
        "_trm() {",
        "    local -a cmds",
        f"    cmds=({' '.join(top)})",
        "    _arguments '1: :->cmds' '*:: :->args'",
        "    case $state in",
        "        cmds)",
        "            _describe 'command' cmds",
        "            ;;",
        "        args)",
        "            case $words[1] in",
    ]
    for group, subs in sorted(groups.items()):
        lines.append(f"                {group})")
        lines.append(f"                    _values 'subcommand' {' '.join(subs)}")
        lines.append("                    ;;")
    lines.append("                *)")
    lines.append("                    ;;")
    lines.append("            esac")
    lines.append("            ;;")
    lines.append("    esac")
    lines.append("}")
    lines.append("compdef _trm trm")
    return "\n".join(lines) + "\n"


def _build_fish() -> str:
    top, groups = _names()
    lines = []
    for name in top:
        lines.append(f'complete -c trm -f -n "__fish_use_subcommand" -a "{name}"')
    for group, subs in sorted(groups.items()):
        for sub in subs:
            lines.append(
                f'complete -c trm -f -n "__fish_seen_subcommand_from {group}" -a "{sub}"'
            )
    return "\n".join(lines) + "\n"


_BUILDERS = {
    "bash": _build_bash,
    "zsh": _build_zsh,
    "fish": _build_fish,
}


def build_script(shell: str) -> str:
    """Return the completion script for ``shell`` (``bash`` / ``zsh`` / ``fish``)."""
    builder = _BUILDERS.get(shell)
    if builder is None:
        raise ValueError(f"unsupported shell: {shell!r}")
    return builder()


def handler(args: argparse.Namespace) -> int:
    """Print the completion script to stdout and return 0."""
    print(build_script(args.shell))
    return 0


def add_subparsers(subparsers: argparse._SubParsersAction) -> None:
    parser = subparsers.add_parser("completion", help="print a shell completion script")
    parser.add_argument("shell", choices=("bash", "zsh", "fish"), help="target shell")
    parser.set_defaults(handler=handler)


__command_meta__ = {
    "completion": {
        "summary": "Print a shell completion script (bash / zsh / fish)",
        "args": "<bash|zsh|fish>",
        "examples": ["trm completion bash", "source <(trm completion bash)"],
        "tags": ["cli", "shell"],
        "risk": "low",
    }
}


__all__ = ["add_subparsers", "build_script", "handler"]
