# matte-black ¡ª Trimum Ubuntu Theme
export TRIMUM_THEME_NAME="matte-black"
export TRIMUM_THEME_VARIANT="dark"
export TRIMUM_BG="#1a1a1a"
export TRIMUM_SURFACE="#222222"
export TRIMUM_OVERLAY="#2e2e2e"
export TRIMUM_SUBTEXT="#5e5e5e"
export TRIMUM_TEXT="#b4b4b4"
export TRIMUM_ACCENT="#b4b4b4"
export TRIMUM_RED="#b4b4b4"
export TRIMUM_GREEN="#b4b4b4"
export TRIMUM_YELLOW="#b4b4b4"
export TRIMUM_BLUE="#b4b4b4"
export TRIMUM_PINK="#b4b4b4"
export TRIMUM_GTK_THEME="matte-black"
export TRIMUM_ICON_THEME="matte-black"
export TRIMUM_CURSOR_THEME="Yaru"
export TRIMUM_TERMINAL_THEME="matte-black"
export TRIMUM_WALLPAPER="themes/matte-black/backgrounds/default.jpg"
