# vantablack ¡ª Trimum Ubuntu Theme
export TRIMUM_THEME_NAME="vantablack"
export TRIMUM_THEME_VARIANT="dark"
export TRIMUM_BG="#000000"
export TRIMUM_SURFACE="#0a0a0a"
export TRIMUM_OVERLAY="#1a1a1a"
export TRIMUM_SUBTEXT="#555555"
export TRIMUM_TEXT="#cccccc"
export TRIMUM_ACCENT="#00ffaa"
export TRIMUM_RED="#ff3355"
export TRIMUM_GREEN="#00cc88"
export TRIMUM_YELLOW="#ffaa33"
export TRIMUM_BLUE="#33aaff"
export TRIMUM_PINK="#ff33aa"
export TRIMUM_GTK_THEME="vantablack"
export TRIMUM_ICON_THEME="vantablack"
export TRIMUM_CURSOR_THEME="Yaru"
export TRIMUM_TERMINAL_THEME="vantablack"
export TRIMUM_WALLPAPER="themes/vantablack/backgrounds/default.jpg"
