# hackerman ¡ª Trimum Ubuntu Theme
export TRIMUM_THEME_NAME="hackerman"
export TRIMUM_THEME_VARIANT="dark"
export TRIMUM_BG="#0c0c0c"
export TRIMUM_SURFACE="#141414"
export TRIMUM_OVERLAY="#282828"
export TRIMUM_SUBTEXT="#558855"
export TRIMUM_TEXT="#33ff33"
export TRIMUM_ACCENT="#00ff00"
export TRIMUM_RED="#ff0033"
export TRIMUM_GREEN="#00ff00"
export TRIMUM_YELLOW="#ffff00"
export TRIMUM_BLUE="#0066ff"
export TRIMUM_PINK="#ff00ff"
export TRIMUM_GTK_THEME="hackerman"
export TRIMUM_ICON_THEME="hackerman"
export TRIMUM_CURSOR_THEME="Yaru"
export TRIMUM_TERMINAL_THEME="hackerman"
export TRIMUM_WALLPAPER="themes/hackerman/backgrounds/default.jpg"
